name: Latest Youtube Videos
on:
  schedule:
     # Runs every hour
     - cron: '0 " " " "'
   workflow_dispatch:

   jobs:
      update-readme-with-youtube:
        name: Udate this repo's README with latest videos from Youtube
        runs-on: ubuntu-latest
        steps:
          - uses: action/checkout@v2
          - uses: gautamkrisnnar/blog-post-workflow@master
            with:
             comment_tag_name: "YOUTUBE-VIDEOS-LIST"
             feed_list: "https://www.youtube.com/@tapfumamundondo8256/featured"
             
